MovieDemo/Controllers/HomeController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MovieDemo.Models.DatabaseConnection;
using MovieDemo.Models.Services;
using ReflectionIT.Mvc.Paging;

namespace MovieDemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly MovieDemoDataContext _databaseConnection;
        public HomeController(MovieDemoDataContext databaseConnection)
        {
            _databaseConnection = databaseConnection;
        }
        /// <summary>
        /// Home page
        /// </summary>
        /// <returns></returns>
        public IActionResult Index(int page = 1)
        {
            //fetch all movies from json object
            var movies = new APIFactory().GetAllMovies(new AppKey().FetchAllMoviesUrl).Result.ToList();

            //paginate movies
            var model =  PagingList.Create(movies, 10, page);
            return View(model);
        }
        /// <summary>
        /// Home page
        /// </summary>
        /// <returns></returns>
        public IActionResult ViewMovie(long movieId)
        {
            //fetch al movies and query single movie by ID
            var movie = new APIFactory().GetAllMovies(new AppKey().FetchAllMoviesUrl).Result.ToList()
                .SingleOrDefault(n=>n.id == movieId);
            return View(movie);
        }

        public IActionResult Privacy()
        {
            return View();
        }
        /// <summary>
        /// Display error page for error 400*,500*
        /// </summary>
        /// <returns></returns>
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View();
        }
    }
}

MovieDemo/Controllers/UserFavouriteMovieController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieDemo.Models.DatabaseConnection;
using MovieDemo.Models.Encryption;
using MovieDemo.Models.Entities;
using MovieDemo.Models.Enum;
using MovieDemo.Models.Services;
using Newtonsoft.Json;
using ReflectionIT.Mvc.Paging;

namespace MovieDemo.Controllers
{
    public class UserFavouriteMovieController : Controller
    {
        private readonly MovieDemoDataContext _databaseConnection;
        public UserFavouriteMovieController(MovieDemoDataContext databaseConnection)
        {
            _databaseConnection = databaseConnection;
        }
        /// <summary>
        /// Get all user favorite movies
        /// </summary>
        /// <returns></returns>
        [SessionExpireFilter]
        public IActionResult Index(int page = 1)
        {
            //get user ID from session
            var userId = Convert.ToInt64(HttpContext.Session.GetString("MovieDemoLoggedInUserId"));

            //get favorite data from DB
            var userFavMovies = _databaseConnection.UserFavouriteMovies.Where(n => n.AppUserId == userId);

            //get all movies
            var movies = new APIFactory().GetAllMovies(new AppKey().FetchAllMoviesUrl).Result.ToList();
            var userMovies = from a in movies
                join b in userFavMovies on a.id equals b.MovieId
                where b.AppUserId == userId
                select a;

            //paginate movies        
            var model = PagingList.Create(userMovies, 10, page);
            return View(model);
        }
        /// <summary>
        /// This method adds a movies to a user favorite list
        /// </summary>
        /// <param name="movieId"></param>
        /// <returns></returns>
        [SessionExpireFilter]
        public IActionResult AddMovieToFavoriteList(long movieId)
        {
            var userId = Convert.ToInt64(HttpContext.Session.GetString("MovieDemoLoggedInUserId"));
            var favoriteMovieExist =
                _databaseConnection.UserFavouriteMovies.Where(n =>
                    n.MovieId == movieId && n.AppUserId == userId).ToList();
            if (favoriteMovieExist.Count <= 0)
            {
                //populate object with values
                var favoriteMovie = new UserFavouriteMovie
                {
                    CreatedBy = userId,
                    LastModifiedBy = userId,
                    DateCreated = DateTime.Now,
                    DateLastModified = DateTime.Now,
                    MovieId = movieId,
                    AppUserId = userId
                };

                //save transaction
                _databaseConnection.UserFavouriteMovies.Add(favoriteMovie);
                _databaseConnection.SaveChanges();

                //fetch user with all favorite movies
                var user = _databaseConnection.AppUsers.Include(n => n.UserFavouriteMovies).SingleOrDefault(n => n.AppUserId == userId);

                //save user object and user id in session
                HttpContext.Session.SetString("MovieDemoLoggedInUser", JsonConvert.SerializeObject(user));

                TempData["display"] = "You have successfully added the movie to your favorite list!";
                TempData["notificationtype"] = NotificationType.Success.ToString();
                return RedirectToAction("Index");
            }

            TempData["display"] = "Invalid request!";
            TempData["notificationtype"] = NotificationType.Error.ToString();
            return RedirectToAction("Index");
        }
        /// <summary>
        /// This method removes a movies to a user favorite list
        /// </summary>
        /// <param name="movieId"></param>
        /// <returns></returns>
        [SessionExpireFilter]
        public IActionResult RemoveMovieToFavoriteList(long movieId)
        {
            //get user ID from session
            var userId = Convert.ToInt64(HttpContext.Session.GetString("MovieDemoLoggedInUserId"));

            var favoriteMovie =
                _databaseConnection.UserFavouriteMovies.SingleOrDefault(n =>
                    n.MovieId == movieId && n.AppUserId == userId);
            if (favoriteMovie != null && favoriteMovie.UserFavouriteMovieId > 0)
            {
                //save transaction
                _databaseConnection.UserFavouriteMovies.Remove(favoriteMovie);
                _databaseConnection.SaveChanges();


                //fetch user with all favorite movies
                var user = _databaseConnection.AppUsers.Include(n => n.UserFavouriteMovies).SingleOrDefault(n => n.AppUserId == userId);

                //save user object and user id in session
                HttpContext.Session.SetString("MovieDemoLoggedInUser", JsonConvert.SerializeObject(user));

                TempData["display"] = "You have successfully removed the movie from your favorite list!";
                TempData["notificationtype"] = NotificationType.Success.ToString();
                return RedirectToAction("Index");
            }

            TempData["display"] = "Invalid request!";
            TempData["notificationtype"] = NotificationType.Error.ToString();
            return RedirectToAction("Index");
        }
    }
}

MovieDemo/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Http
@using MovieDemo.Models.Entities
@using Newtonsoft.Json
@model ReflectionIT.Mvc.Paging.PagingList<MovieDemo.Models.Entities.Movie>
@addTagHelper *,ReflectionIT.Mvc.Paging
@{
    ViewData["Title"] = "Home Page";
    var user = new AppUser();
    if (Context.Session.GetString("MovieDemoLoggedInUser") != null)
    {
        var userString = Context.Session.GetString("MovieDemoLoggedInUser");
        user = JsonConvert.DeserializeObject<AppUser>(userString);
    }
}
<div class="text-center">
    <nav aria-label="Movie Demo">
        <vc:pager paging-list="@Model"></vc:pager>
    </nav>
</div> <!-- end .text-right -->
<div class="row">
    @foreach (var item in Model)
    {
        var time = TimeSpan.FromMinutes(item.runtime);
        var fromTimeString = time.ToString("hh':'mm");
        <div class="col-md-4 col-sm-6" style="min-height: 300px !important">
            <div class="property-card">
                <div class="property-image" style="background: url('@item.posterPath') center center/cover no-repeat;">
                    @if (user.AppUserId > 0)
                    {
                        if (user.UserFavouriteMovies.SingleOrDefault(n => n.AppUserId == user.AppUserId && n.MovieId == item.id) == null)
                        {
                            <span class="property-label label label-warning">
                                <a style="color: white" href="@Url.Action("AddMovieToFavoriteList", "UserFavouriteMovie", new {movieId = item.id})">
                                    Add to Favorite
                                </a>

                            </span>
                        }
                        else
                        {
                            <span class="property-label label label-warning">
                                <a style="color: white" href="@Url.Action("RemoveMovieToFavoriteList", "UserFavouriteMovie", new {movieId = item.id})">
                                    Remove Favorite
                                </a>

                            </span>
                        }
                    }

                </div>

                <div class="property-content">
                    <div class="listingInfo">
                        <div class="">
                            <h5 class="text-success m-t-0">$@($"{item.budget:n0}")</h5>
                        </div>
                        <div class="">
                            <h3 class="text-overflow">
                                <a href="#" class="text-dark">@item.title</a>
                            </h3>
                            <p class="text-muted text-overflow"><i class="mdi mdi-calendar m-r-5"></i>@item.overview?.Substring(0, item.overview.Length)...</p>

                            <div class="row text-center">
                                <div class="col-xs-4">
                                    <h6>
                                        @(new DateTime(item.releaseDate[0], item.releaseDate[1],
                                            item.releaseDate[2]).ToString("D"))
                                    </h6>
                                    <p class="text-overflow" title="Square Feet">Date Released</p>
                                </div>
                                <div class="col-xs-4">
                                    <h5>@fromTimeString</h5>
                                    <p class="text-overflow" title="Bedrooms">Runtime</p>
                                </div>
                                <div class="col-xs-4">
                                    <h5>@item.voteAverage</h5>
                                    <p class="text-overflow" title="Parking Space">Vote Average</p>
                                </div>
                            </div>

                            <div class="m-t-20">

                                <a href="@Url.Action("ViewMovie", new {movieId = item.id})" target="_blank" class="btn btn-primary btn-block waves-effect waves-light">View Movie</a>
                            </div>
                        </div>
                    </div>
                    <!-- end. Card actions -->
                </div>
                <!-- /inner row -->
            </div>
            <br/>
            <br/>
            <br/>
            <!-- End property item -->
        </div>
        <!-- end col -->
    }
</div>


<div class="text-center">
    <nav aria-label="Movie Demo">
        <vc:pager paging-list="@Model"></vc:pager>
    </nav>
</div> <!-- end .text-right -->

MovieDemo/Views/Home/ViewMovie.cshtml
@model MovieDemo.Models.Entities.Movie
@{
    Layout = "_Layout";
    ViewData["Title"] = Model.title;

    var time = TimeSpan.FromMinutes(Model.runtime);
    var fromTimeString = time.ToString("hh':'mm");
}
<div class="property-detail-wrapper">
    <div class="row">
        <div class="col-md-8">
            <div class="">
                <ul class="bxslider property-slider">
                    @if (Model.vidoes != null && Model.vidoes.Count > 0)
                    {
                        @foreach (var item in Model.vidoes)
                        {
                            <li>
                                <iframe class="viewImage" scrolling="no"
                                        style="height: 900px; position: relative; width: 600px;"
                                        src="https://www.youtube.com/embed/@item.key">
                                </iframe>
                            </li>
                        }
                    }
                    else
                    {
                        <li>
                            <img src="@Model.posterPath" class="viewImage" alt="slide-image"/>
                        </li>
                    }


                </ul>
                <div id="bx-pager" class="text-center hide-phone">
                    @if (Model.vidoes != null && Model.vidoes.Count > 0)
                    {
                        var index = 0;
                        @foreach (var item in Model.vidoes)
                        {
                            <a data-slide-index="@index" href="">
                                <img src="@Model.posterPath" alt="slide-image" height="70"/>
                            </a>
                            index = index + 1;
                        }
                    }
                    else
                    {
                        <a data-slide-index="0" href="">
                            <img src="@Model.posterPath" alt="slide-image" height="70"/>
                        </a>
                    }
                </div>


            </div>
            <!-- end slider -->

            <div class="m-t-30">
                <h3>@Model.title</h3>
                <p class="text-muted text-overflow">
                    <i class="mdi mdi-calendar m-r-5"></i>
                    @(new DateTime(Model.releaseDate[0], Model.releaseDate[1],
                        Model.releaseDate[2]).ToString("D"))
                </p>

                <p class="m-t-20">
                    @Model.overview
                </p>

                <h4 class="m-t-30 m-b-20">Movie Genre</h4>

                <div class="row">
                    <div class="col-sm-4">
                        <ul class="list-unstyled proprerty-features">
                            @foreach (var item in Model.genres)
                            {
                                <li>
                                    <i class="mdi mdi-check-circle-outline text-success m-r-5"></i>
                                    @item.name
                                </li>
                            }
                        </ul>

                    </div> <!--- end col -->

                </div> <!-- end row -->
            </div> <!-- end m-t-30 -->

        </div> <!-- end col -->

        <div class="col-md-4">
            <div class="card-box">
                <div class="table-responsive">
                    <table class="table table-bordered m-b-0">
                        <tbody>
                        <tr>
                            <th scope="row">Budget:</th>
                            <td><span class="label label-success">$@($"{Model.budget:n0}")</span></td>
                        </tr>
                        <tr>
                            <th scope="row">Home Page: </th>
                            <td>
                                <a href="@Model.homepage" target="_blank" class="label label-success">@Model.homepage</a>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">Runtime: </th>
                            <td>
                                <span class="label label-success">@fromTimeString</span>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">Status: </th>
                            <td>
                                <span class="label label-success">@Model.status</span>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">Vote Average:</th>
                            <td><span class="label label-success">@Model.voteAverage</span></td>
                        </tr>

                        </tbody>
                    </table>
                </div>
            </div>
            <!-- end card-box -->

        </div> <!-- end col -->
    </div> <!-- end row -->
</div>